import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { Button, Link, TextField, Text } from '@aws-amplify/ui-react';


export default function Home() {

  const [currentUser, setCurrentUser] = useState(null);
  const [loading,setLoading] = useState(true);

  async function callWhoami(){
    const res = await fetch('api/whoami');
    //console.log(res);

    if (res.status === 200){
      //console.log(res.json());

      return await res.json();
      /* res.json().then(
        (data) => data.username
      ).catch((err)=> console.log(err)); */
      //return res.json().username;
    }
    else{
      return null;
    }
  }

  useEffect(()=>{

    callWhoami().then(
      (res) => {

        if (res === null){
          setCurrentUser(res);
        }else{
          //console.log(res);

          setCurrentUser(res.username);
/*           res.then(
            (data) => setCurrentUser(data.username)
          ).catch((err)=> console.log(err)); */
        }
        
        setLoading(false);
    }
    ).catch((err)=> {
      console.log(err);
      setLoading(false);
    });

  },[]);




  if (loading === true) {

  return (
    <div>
      <h1>Loading.... </h1>
    </div>
  )

  }
  else if (currentUser === null) {

    return (
      <div className={styles.container}>
        <Head>
          <title>Current User Info</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
          <h1 className={styles.title}>
            {'Welcome everyone. To sign in please use the link below'}
          </h1>

        <Link href='/login'>Proceed to Login..</Link>
          </main>
          
      </div>
    )

  }
  else
  
  {

  return (
    <div className={styles.container}>
      <Head>
        <title>Current User Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          {'Welcome to this wonderful app '+ currentUser}
        </h1>
          <Link href='/signout'>Sign Out</Link>
          <AddNote></AddNote>

      </main>
        
    </div>
  )
  }
}

/* function ListNotes(){
  const [notes,setNotes] = useState([]);

  return 
  (
    <div className={styles.container}>
      {
        notes.map(
          (note) => {

          }
        )
      }
    </div>
  )

} */

function AddNote(){

  const [name, setName] = useState('');
  const [desc, setDesc] = useState('');
  const [result,setResult] = useState('');

  function descChange(e){
    setDesc(e.currentTarget.value)
  }

  function nameChange(e){
    setName(e.currentTarget.value)
  }

  async function createNote(){

    const res = await fetch('api/addnote?name='+name+'&description='+desc);
    
    const body = await res.json();
    console.log(body);
    if (res.status === 200){
       setResult('note created sucessfully');
    }else{
      setResult('Some issue with creation of note');
    }
  }

  return (
    <div className={styles.container}>
      <TextField label="Name:" placeholder='provide a name for the note' onChange={nameChange}></TextField>
      <TextField label="Description:" placeholder='provide a description for the note'  onChange={descChange}></TextField>
      <Button onClick={createNote}>Add Note</Button>
      <Text>{result}</Text>
    </div>
  )
}
