import Head from 'next/head'
//import Image from 'next/image'
import { Auth } from "aws-amplify";
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { Button } from '@aws-amplify/ui-react';


export default function Home() {
  const [session, setSession] = useState({currentUser: null});
  const [loading,setLoading] = useState(true);
  const [welcomeMessage,setWelcomeMessage] = useState('');

  async function getSession() {
  
    //const SSR = withSSRContext({ req });
    const data  = await Auth.currentSession();
    //console.log('printing session');
    //console.log(data);
    if (data !== null){
      return {
          currentUser: data
      }
    } else{
      return {
          currentUser: null
      }
    }
  }

  async function callWhoami(){
    const res = await fetch('api/whoami');
    console.log(res);
  }


  useEffect(()=>{

    callWhoami();
    getSession().then((data)=>{


      setSession(data);
      //console.log(data);
      //console.log('printing from then');
      //console.log(session);
      setWelcomeMessage('Welcome to next js: '+data.currentUser.accessToken.payload.username);   
      setLoading(false);
    }).catch(
      (err) => {
        setSession(err);
      //console.log(session);
      setWelcomeMessage('Welcome everyone');
      setLoading(false);
      }      
    )
    

    

  },[]);

  if (loading === true) {

  return (
    <div>
      <h1>Loading.... </h1>
    </div>
  )

  }
  else {

  return (
    <div className={styles.container}>
      <Head>
        <title>Current User Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {welcomeMessage}
        </h1>
        <Button onClick={()=>Auth.signOut()}>Sign Out</Button>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
  }
}
